name: CI

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

permissions: {}

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable, 1.58.1, 1.17.0]
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - name: Install Rust ${{ matrix.rust }}
        env:
          RUST_TOOLCHAIN: ${{ matrix.rust }}
        run: |
          rustup toolchain install "$RUST_TOOLCHAIN" --profile minimal
          rustup default "$RUST_TOOLCHAIN"
      - run: cargo build --features bench
        if: matrix.rust == 'nightly'
      - run: cargo test --features bench
        if: matrix.rust == 'nightly'
      # - run: cargo bench --features bench
        # if: matrix.rust == 'nightly'
      - run: cargo build
      - run: cargo test
        if: matrix.rust != '1.17.0'
